services:
  database:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=mydb
    volumes:
      - 'fastapi-db-data:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser"]
      interval: 30s
      timeout: 30s
      retries: 3
  fastapi:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://dbuser:pass123@database:5432/mydb
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/data/app
    depends_on:
      database:
        condition: service_healthy
volumes:
  fastapi-db-data:
