apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres-service
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 5432
  selector:
    app: db
  type: ClusterIP