apiVersion: apps/v1
kind: Deployment
metadata:
  name:  postgres-deployment
  namespace: default
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc
      containers:
      - name: postgres
        image: postgres:16
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-volume
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 256Mi
        env:
          - name: POSTGRES_PASSWORD
            value: pass123
          - name: POSTGRES_USER
            value: dbuser
          - name: POSTGRES_DB
            value: mydb
        ports:
        - containerPort: 5432